//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pz18
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bituchet2Entities : DbContext
    {
        public bituchet2Entities()
            : base("name=bituchet2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddedDesk> AddedDesk { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<RepairRequests> RepairRequests { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
